// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProxyHarbor.Infrastructure;

#nullable disable

namespace ProxyHarbor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProxyHarborDbContext))]
    [Migration("20260809130858_ValidationAttemptTelemetry")]
    partial class ValidationAttemptTelemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProxyHarbor.Domain.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SentToTelegram")
                        .HasColumnType("boolean");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("TelegramConfigured")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status", "FinishedAt");

                    b.ToTable("BackupRuns");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.CollectionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AliveProxies")
                        .HasColumnType("integer");

                    b.Property<bool>("CandidateLimitReached")
                        .HasColumnType("boolean");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewProxies")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesSucceeded")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesTruncated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ProxyEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CheckLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailedChecks")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ExitIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastValidationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastValidationDeferred")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulChecks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LastValidationAttemptAt");

                    b.HasIndex("NextCheckAt", "CheckLeaseUntil");

                    b.HasIndex("Status", "LastSeenAt");

                    b.HasIndex("Host", "Port", "Protocol")
                        .IsUnique();

                    b.HasIndex("Status", "LatencyMs", "LastCheckedAt");

                    b.HasIndex("Status", "Protocol", "LatencyMs", "LastCheckedAt");

                    b.ToTable("Proxies");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ProxySource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultProtocol")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastItemCount")
                        .HasColumnType("integer");

                    b.Property<bool>("LastResultTruncated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("NextFetchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Enabled", "ConsecutiveFailures");

                    b.HasIndex("Enabled", "NextFetchAt");

                    b.ToTable("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
