// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProxyHarbor.Infrastructure;

#nullable disable

namespace ProxyHarbor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProxyHarborDbContext))]
    [Migration("20260809194110_AddSourceHttpValidators")]
    partial class AddSourceHttpValidators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProxyHarbor.Domain.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SentToTelegram")
                        .HasColumnType("boolean");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("TelegramConfigured")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status", "FinishedAt");

                    b.ToTable("BackupRuns", t =>
                        {
                            t.HasCheckConstraint("CK_BackupRuns_Result", "\"SizeBytes\" >= 0 AND (NOT \"SentToTelegram\" OR \"TelegramConfigured\") AND (\"Status\" <> 'completed' OR NOT \"TelegramConfigured\" OR \"SentToTelegram\")");

                            t.HasCheckConstraint("CK_BackupRuns_State", "\"Status\" IN ('running', 'completed', 'failed') AND ((\"Status\" = 'running') = (\"FinishedAt\" IS NULL)) AND (\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\")");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.CollectionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AliveProxies")
                        .HasColumnType("integer");

                    b.Property<bool>("CandidateLimitReached")
                        .HasColumnType("boolean");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewProxies")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesSucceeded")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesTruncated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Runs", t =>
                        {
                            t.HasCheckConstraint("CK_Runs_Counters", "\"SourcesProcessed\" >= 0 AND \"SourcesSucceeded\" >= 0 AND \"SourcesFailed\" >= 0 AND \"SourcesSkipped\" >= 0 AND \"SourcesTruncated\" >= 0 AND \"CandidatesFound\" >= 0 AND \"NewProxies\" >= 0 AND \"AliveProxies\" >= 0 AND \"SourcesSucceeded\"::bigint + \"SourcesFailed\"::bigint = \"SourcesProcessed\" AND \"SourcesTruncated\" <= \"SourcesSucceeded\" AND \"NewProxies\" <= \"CandidatesFound\"");

                            t.HasCheckConstraint("CK_Runs_State", "\"Status\" IN ('running', 'completed', 'failed') AND ((\"Status\" = 'running') = (\"FinishedAt\" IS NULL)) AND (\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\")");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ProxyEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CheckLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailedChecks")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ExitIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastValidationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastValidationDeferred")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulChecks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckLeaseId");

                    b.HasIndex("LastCheckedAt")
                        .HasDatabaseName("IX_Proxies_Alive_LastCheckedAt")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("LastValidationAttemptAt");

                    b.HasIndex("NextCheckAt", "CheckLeaseUntil");

                    b.HasIndex("Protocol", "LastCheckedAt")
                        .HasDatabaseName("IX_Proxies_Alive_Protocol_LastCheckedAt")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("Status", "LastSeenAt");

                    b.HasIndex("Host", "Port", "Protocol")
                        .IsUnique();

                    b.HasIndex("LatencyMs", "SuccessfulChecks", "Id", "LastCheckedAt")
                        .IsDescending(false, true, false, false)
                        .HasDatabaseName("IX_Proxies_Alive_PublicOrder")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("Protocol", "LatencyMs", "SuccessfulChecks", "Id", "LastCheckedAt")
                        .IsDescending(false, false, true, false, false)
                        .HasDatabaseName("IX_Proxies_Alive_Protocol_PublicOrder")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.ToTable("Proxies", t =>
                        {
                            t.HasCheckConstraint("CK_Proxies_CheckCounters", "\"SuccessfulChecks\" >= 0 AND \"FailedChecks\" >= 0 AND \"ConsecutiveFailedChecks\" >= 0 AND \"ConsecutiveFailedChecks\" <= \"FailedChecks\" AND \"SuccessfulChecks\"::bigint + \"FailedChecks\"::bigint <= 2147483647");

                            t.HasCheckConstraint("CK_Proxies_DeferredAttempt", "NOT \"LastValidationDeferred\" OR \"LastValidationAttemptAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Proxies_Identity", "\"Port\" BETWEEN 1 AND 65535 AND \"Protocol\" BETWEEN 0 AND 3 AND \"Status\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_Proxies_Latency", "\"LatencyMs\" IS NULL OR \"LatencyMs\" >= 0");

                            t.HasCheckConstraint("CK_Proxies_Lease", "(\"CheckLeaseUntil\" IS NULL) = (\"CheckLeaseId\" IS NULL)");

                            t.HasCheckConstraint("CK_Proxies_Timeline", "\"LastSeenAt\" >= \"FirstSeenAt\"");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ProxySource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultProtocol")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HttpETag")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("HttpLastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastItemCount")
                        .HasColumnType("integer");

                    b.Property<bool>("LastResultTruncated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("NextFetchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Enabled", "ConsecutiveFailures");

                    b.HasIndex("Enabled", "NextFetchAt");

                    b.ToTable("Sources", t =>
                        {
                            t.HasCheckConstraint("CK_Sources_Counters", "\"LastItemCount\" >= 0 AND \"ConsecutiveFailures\" >= 0");

                            t.HasCheckConstraint("CK_Sources_FetchTimeline", "\"LastSucceededAt\" IS NULL OR (\"LastFetchedAt\" IS NOT NULL AND \"LastSucceededAt\" <= \"LastFetchedAt\")");

                            t.HasCheckConstraint("CK_Sources_ProtocolPriority", "\"DefaultProtocol\" BETWEEN 0 AND 3 AND \"Priority\" BETWEEN -10000 AND 10000");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ValidationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Alive")
                        .HasColumnType("integer");

                    b.Property<int>("Checked")
                        .HasColumnType("integer");

                    b.Property<int>("Claimed")
                        .HasColumnType("integer");

                    b.Property<int>("Deferred")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status", "FinishedAt");

                    b.ToTable("ValidationRuns", t =>
                        {
                            t.HasCheckConstraint("CK_ValidationRuns_Counters", "\"Claimed\" >= 0 AND \"Checked\" >= 0 AND \"Alive\" >= 0 AND \"Deferred\" >= 0 AND \"Checked\"::bigint + \"Deferred\"::bigint <= \"Claimed\" AND \"Alive\" <= \"Checked\"");

                            t.HasCheckConstraint("CK_ValidationRuns_State", "\"Status\" IN ('running', 'completed', 'failed') AND ((\"Status\" = 'running') = (\"FinishedAt\" IS NULL)) AND (\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\")");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
