// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProxyHarbor.Infrastructure;

#nullable disable

namespace ProxyHarbor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProxyHarborDbContext))]
    [Migration("20260828194922_AddVpnSourceFetchBackoff")]
    partial class AddVpnSourceFetchBackoff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProxyHarbor.Domain.BackupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SentToTelegram")
                        .HasColumnType("boolean");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("TelegramConfigured")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status", "FinishedAt");

                    b.ToTable("BackupRuns", t =>
                        {
                            t.HasCheckConstraint("CK_BackupRuns_Result", "\"SizeBytes\" >= 0 AND (NOT \"SentToTelegram\" OR \"TelegramConfigured\") AND (\"Status\" <> 'completed' OR NOT \"TelegramConfigured\" OR \"SentToTelegram\")");

                            t.HasCheckConstraint("CK_BackupRuns_State", "\"Status\" IN ('running', 'completed', 'failed') AND ((\"Status\" = 'running') = (\"FinishedAt\" IS NULL)) AND (\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\")");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.CheckerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("AliveChecks")
                        .HasColumnType("bigint");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<long>("CompletedChecks")
                        .HasColumnType("bigint");

                    b.Property<int>("Concurrency")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CurrentLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeploymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HostKeyFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLeaseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RemoteAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SshPort")
                        .HasColumnType("integer");

                    b.Property<string>("SshUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("LastHeartbeatAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CheckerNodes");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.CollectionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AliveProxies")
                        .HasColumnType("integer");

                    b.Property<bool>("CandidateLimitReached")
                        .HasColumnType("boolean");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewProxies")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesSucceeded")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesTruncated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Runs", t =>
                        {
                            t.HasCheckConstraint("CK_Runs_Counters", "\"SourcesProcessed\" >= 0 AND \"SourcesSucceeded\" >= 0 AND \"SourcesFailed\" >= 0 AND \"SourcesSkipped\" >= 0 AND \"SourcesTruncated\" >= 0 AND \"CandidatesFound\" >= 0 AND \"NewProxies\" >= 0 AND \"AliveProxies\" >= 0 AND \"SourcesSucceeded\"::bigint + \"SourcesFailed\"::bigint = \"SourcesProcessed\" AND \"SourcesTruncated\" <= \"SourcesSucceeded\" AND \"NewProxies\" <= \"CandidatesFound\"");

                            t.HasCheckConstraint("CK_Runs_State", "\"Status\" IN ('running', 'completed', 'failed') AND ((\"Status\" = 'running') = (\"FinishedAt\" IS NULL)) AND (\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\")");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ProxyEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckLeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CheckLeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailedChecks")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset?>("CurrentAliveSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExitIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FirstAliveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAliveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastValidationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastValidationDeferred")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulChecks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckLeaseId");

                    b.HasIndex("LastCheckedAt")
                        .HasDatabaseName("IX_Proxies_Alive_LastCheckedAt")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("LastValidationAttemptAt");

                    b.HasIndex("NextCheckAt", "CheckLeaseUntil");

                    b.HasIndex("Protocol", "LastCheckedAt")
                        .HasDatabaseName("IX_Proxies_Alive_Protocol_LastCheckedAt")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("Status", "LastSeenAt");

                    b.HasIndex("Host", "Port", "Protocol")
                        .IsUnique();

                    b.HasIndex("LatencyMs", "SuccessfulChecks", "Id", "LastCheckedAt")
                        .IsDescending(false, true, false, false)
                        .HasDatabaseName("IX_Proxies_Alive_PublicOrder")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("Protocol", "LatencyMs", "SuccessfulChecks", "Id", "LastCheckedAt")
                        .IsDescending(false, false, true, false, false)
                        .HasDatabaseName("IX_Proxies_Alive_Protocol_PublicOrder")
                        .HasFilter("\"Status\" = 1")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.ToTable("Proxies", t =>
                        {
                            t.HasCheckConstraint("CK_Proxies_AliveTimeline", "(\"FirstAliveAt\" IS NULL) = (\"LastAliveAt\" IS NULL) AND (\"FirstAliveAt\" IS NULL OR (\"FirstAliveAt\" >= \"FirstSeenAt\" AND \"LastAliveAt\" >= \"FirstAliveAt\")) AND (\"CurrentAliveSince\" IS NULL OR (\"Status\" = 1 AND \"FirstAliveAt\" IS NOT NULL AND \"CurrentAliveSince\" >= \"FirstAliveAt\" AND \"LastAliveAt\" >= \"CurrentAliveSince\"))");

                            t.HasCheckConstraint("CK_Proxies_CheckCounters", "\"SuccessfulChecks\" >= 0 AND \"FailedChecks\" >= 0 AND \"ConsecutiveFailedChecks\" >= 0 AND \"ConsecutiveFailedChecks\" <= \"FailedChecks\" AND \"SuccessfulChecks\"::bigint + \"FailedChecks\"::bigint <= 2147483647");

                            t.HasCheckConstraint("CK_Proxies_DeferredAttempt", "NOT \"LastValidationDeferred\" OR \"LastValidationAttemptAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Proxies_Identity", "\"Port\" BETWEEN 1 AND 65535 AND \"Protocol\" BETWEEN 0 AND 3 AND \"Status\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_Proxies_Latency", "\"LatencyMs\" IS NULL OR \"LatencyMs\" >= 0");

                            t.HasCheckConstraint("CK_Proxies_Lease", "(\"CheckLeaseUntil\" IS NULL) = (\"CheckLeaseId\" IS NULL)");

                            t.HasCheckConstraint("CK_Proxies_StatusEvidence", "(\"Status\" = 0) OR (\"Status\" = 1 AND \"LastCheckedAt\" IS NOT NULL AND \"LatencyMs\" IS NOT NULL AND \"SuccessfulChecks\" > 0) OR (\"Status\" = 2 AND \"LastCheckedAt\" IS NOT NULL AND \"FailedChecks\" > 0)");

                            t.HasCheckConstraint("CK_Proxies_Timeline", "\"LastSeenAt\" >= \"FirstSeenAt\"");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ProxySource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultProtocol")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HttpETag")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("HttpLastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastContentFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastItemCount")
                        .HasColumnType("integer");

                    b.Property<bool>("LastResultTruncated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("NextFetchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Enabled", "ConsecutiveFailures");

                    b.HasIndex("Enabled", "NextFetchAt");

                    b.ToTable("Sources", t =>
                        {
                            t.HasCheckConstraint("CK_Sources_ContentTimeline", "\"LastContentFetchedAt\" IS NULL OR (\"LastFetchedAt\" IS NOT NULL AND \"LastSucceededAt\" IS NOT NULL AND \"LastContentFetchedAt\" <= \"LastFetchedAt\" AND \"LastContentFetchedAt\" <= \"LastSucceededAt\")");

                            t.HasCheckConstraint("CK_Sources_Counters", "\"LastItemCount\" >= 0 AND \"ConsecutiveFailures\" >= 0");

                            t.HasCheckConstraint("CK_Sources_FetchTimeline", "\"LastSucceededAt\" IS NULL OR (\"LastFetchedAt\" IS NOT NULL AND \"LastSucceededAt\" <= \"LastFetchedAt\")");

                            t.HasCheckConstraint("CK_Sources_ProtocolPriority", "\"DefaultProtocol\" BETWEEN 0 AND 3 AND \"Priority\" BETWEEN -10000 AND 10000");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ValidationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Alive")
                        .HasColumnType("integer");

                    b.Property<int>("Checked")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CheckerNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Claimed")
                        .HasColumnType("integer");

                    b.Property<int>("Deferred")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("CheckerNodeId", "StartedAt");

                    b.HasIndex("Status", "FinishedAt");

                    b.ToTable("ValidationRuns", t =>
                        {
                            t.HasCheckConstraint("CK_ValidationRuns_Counters", "\"Claimed\" >= 0 AND \"Checked\" >= 0 AND \"Alive\" >= 0 AND \"Deferred\" >= 0 AND \"Checked\"::bigint + \"Deferred\"::bigint <= \"Claimed\" AND \"Alive\" <= \"Checked\"");

                            t.HasCheckConstraint("CK_ValidationRuns_State", "\"Status\" IN ('running', 'completed', 'failed') AND ((\"Status\" = 'running') = (\"FinishedAt\" IS NULL)) AND (\"FinishedAt\" IS NULL OR \"FinishedAt\" >= \"StartedAt\")");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionUri")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FirstSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulChecks")
                        .HasColumnType("integer");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("FirstSourceId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("Status", "NextCheckAt");

                    b.HasIndex("Host", "Port", "Protocol", "Transport")
                        .IsUnique();

                    b.ToTable("VpnEndpoints", t =>
                        {
                            t.HasCheckConstraint("CK_VpnEndpoints_Counters", "\"SuccessfulChecks\" >= 0 AND \"FailedChecks\" >= 0");

                            t.HasCheckConstraint("CK_VpnEndpoints_Identity", "\"Port\" BETWEEN 1 AND 65535 AND \"Protocol\" BETWEEN 0 AND 7 AND \"Status\" BETWEEN 0 AND 3 AND \"Transport\" IN ('tcp', 'udp')");

                            t.HasCheckConstraint("CK_VpnEndpoints_Timeline", "\"LastSeenAt\" >= \"FirstSeenAt\"");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnEndpointSource", b =>
                {
                    b.Property<Guid>("VpnEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VpnSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VpnEndpointId", "VpnSourceId");

                    b.HasIndex("VpnSourceId");

                    b.ToTable("VpnEndpointSources");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultProtocol")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("NextFetchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Enabled", "NextFetchAt");

                    b.HasIndex("Enabled", "Priority");

                    b.ToTable("VpnSources", t =>
                        {
                            t.HasCheckConstraint("CK_VpnSources_Counters", "\"LastItemCount\" >= 0 AND \"ConsecutiveFailures\" >= 0");

                            t.HasCheckConstraint("CK_VpnSources_FetchTimeline", "\"LastSucceededAt\" IS NULL OR (\"LastFetchedAt\" IS NOT NULL AND \"LastSucceededAt\" <= \"LastFetchedAt\")");

                            t.HasCheckConstraint("CK_VpnSources_ProtocolPriority", "\"DefaultProtocol\" BETWEEN 0 AND 7 AND \"Priority\" BETWEEN -10000 AND 10000");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.AccessBlockRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("UserId");

                    b.HasIndex("Enabled", "ExpiresAt");

                    b.HasIndex("Kind", "Value");

                    b.ToTable("AccessBlockRules", t =>
                        {
                            t.HasCheckConstraint("CK_AccessBlockRules_Kind", "\"Kind\" IN ('ip', 'cidr', 'user')");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("OfferAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PersonalDataConsentAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonalDataConsentVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("ru");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_ActiveTimeline", "\"LastLoginAt\" IS NULL OR \"LastLoginAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_AspNetUsers_PreferredLanguage", "\"PreferredLanguage\" IN ('ru', 'en', 'de', 'fr', 'zh')");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.BackupConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProtectedSecrets")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BackupConfigurations", t =>
                        {
                            t.HasCheckConstraint("CK_BackupConfigurations_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.FreeProxyExportGrant", b =>
                {
                    b.Property<string>("ClientKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAllowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientKey");

                    b.HasIndex("NextAllowedAt");

                    b.ToTable("FreeProxyExportGrants", t =>
                        {
                            t.HasCheckConstraint("CK_FreeProxyExportGrants_Timeline", "\"NextAllowedAt\" > \"LastGrantedAt\"");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.PaymentConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProtectedSecrets")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PaymentConfigurations", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentConfigurations_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentInstrument")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PaymentOrders", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentOrders_Amount", "\"AmountMinor\" > 0 AND \"DurationDays\" BETWEEN 1 AND 3660");

                            t.HasCheckConstraint("CK_PaymentOrders_Currency", "char_length(\"Currency\") = 3 AND \"Currency\" = upper(\"Currency\")");

                            t.HasCheckConstraint("CK_PaymentOrders_Plan", "\"Plan\" IN ('pro', 'unlimited')");

                            t.HasCheckConstraint("CK_PaymentOrders_Status", "\"Status\" IN ('pending', 'paid', 'failed', 'canceled', 'refunded')");

                            t.HasCheckConstraint("CK_PaymentOrders_Timeline", "\"PaidAt\" IS NULL OR (\"PaidAt\" >= \"CreatedAt\" AND \"Status\" IN ('paid', 'refunded'))");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ProxyAccessBucket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BlockedRequests")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("BucketStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProxyItems")
                        .HasColumnType("bigint");

                    b.Property<int>("Requests")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LastSeenAt", "Requests");

                    b.HasIndex("BucketStartedAt", "IpAddress", "UserId", "Endpoint")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("BucketStartedAt", "IpAddress", "UserId", "Endpoint"), false);

                    b.ToTable("ProxyAccessBuckets", t =>
                        {
                            t.HasCheckConstraint("CK_ProxyAccessBuckets_Counters", "\"Requests\" >= 0 AND \"BlockedRequests\" >= 0 AND \"ProxyItems\" >= 0 AND \"BytesSent\" >= 0");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ReferralRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferredUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId")
                        .IsUnique();

                    b.HasIndex("ReferrerUserId", "CreatedAt");

                    b.HasIndex("ReferrerUserId", "Slot")
                        .IsUnique();

                    b.ToTable("ReferralRelationships", t =>
                        {
                            t.HasCheckConstraint("CK_ReferralRelationships_DifferentUsers", "\"ReferrerUserId\" <> \"ReferredUserId\"");

                            t.HasCheckConstraint("CK_ReferralRelationships_Slot", "\"Slot\" BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ReferralReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysGranted")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("PaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferralRelationshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOrderId");

                    b.HasIndex("RewardKey")
                        .IsUnique();

                    b.HasIndex("ReferralRelationshipId", "CreatedAt");

                    b.ToTable("ReferralRewards", t =>
                        {
                            t.HasCheckConstraint("CK_ReferralRewards_Days", "\"DaysGranted\" BETWEEN 1 AND 365");

                            t.HasCheckConstraint("CK_ReferralRewards_Kind", "\"Kind\" IN ('signup', 'purchase')");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.SiteVisitLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("VisitedAt");

                    b.HasIndex("IpAddress", "VisitedAt");

                    b.HasIndex("UserId", "VisitedAt");

                    b.ToTable("SiteVisitLogs");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.SubscriptionAdminAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NewExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewPlan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PreviousExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousPlan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("SubscriptionId", "CreatedAt");

                    b.ToTable("SubscriptionAdminActions");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramBotConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("BotId")
                        .HasColumnType("bigint");

                    b.Property<string>("BotUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProtectedSecrets")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.Property<DateTimeOffset?>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TelegramBotConfigurations", t =>
                        {
                            t.HasCheckConstraint("CK_TelegramBotConfigurations_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MarketingConsentGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketingConsentVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("MarketingConsentWithdrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("MarketingNotificationsEnabled", "IsBlocked", "LastInteractionAt");

                    b.HasIndex("NotificationsEnabled", "IsBlocked", "LastInteractionAt");

                    b.ToTable("TelegramChats");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("OutboundMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TelegramChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("OutboundMessageId");

                    b.HasIndex("TelegramChatId", "CreatedAt");

                    b.ToTable("TelegramConversationMessages", t =>
                        {
                            t.HasCheckConstraint("CK_TelegramConversationMessages_Direction", "\"Direction\" IN ('inbound', 'bot', 'admin')");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramOutboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TelegramChatId")
                        .HasColumnType("uuid");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TelegramChatId", "CreatedAt");

                    b.HasIndex("Status", "AvailableAt", "LeaseUntil");

                    b.ToTable("TelegramOutboundMessages", t =>
                        {
                            t.HasCheckConstraint("CK_TelegramOutboundMessages_Attempts", "\"Attempts\" BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_TelegramOutboundMessages_Kind", "\"Kind\" IN ('text', 'invoice', 'proxy_file')");

                            t.HasCheckConstraint("CK_TelegramOutboundMessages_Status", "\"Status\" IN ('pending', 'processing', 'sent', 'failed', 'canceled')");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramUpdateReceipt", b =>
                {
                    b.Property<long>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UpdateId"));

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("UpdateId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("TelegramUpdateReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_TelegramUpdateReceipts_Transport", "\"Transport\" IN ('webhook', 'polling')");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplaySuffix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("UserApiTokens", t =>
                        {
                            t.HasCheckConstraint("CK_UserApiTokens_Hash", "octet_length(\"SecretHash\") = 32");

                            t.HasCheckConstraint("CK_UserApiTokens_Timeline", "\"LastUsedAt\" IS NULL OR \"LastUsedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserApiTokenRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Query")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserApiTokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserApiTokenId", "RequestedAt");

                    b.HasIndex("UserId", "RequestedAt");

                    b.ToTable("UserApiTokenRequests", t =>
                        {
                            t.HasCheckConstraint("CK_UserApiTokenRequests_Duration", "\"DurationMs\" >= 0");

                            t.HasCheckConstraint("CK_UserApiTokenRequests_ItemCount", "\"ItemCount\" IS NULL OR \"ItemCount\" >= 0");

                            t.HasCheckConstraint("CK_UserApiTokenRequests_Status", "\"StatusCode\" BETWEEN 100 AND 599");
                        });
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("UserId", "DeliveredAt", "CreatedAt");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Plan", "Status", "ExpiresAt");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_Plan", "\"Plan\" IN ('free', 'pro', 'unlimited')");

                            t.HasCheckConstraint("CK_Subscriptions_Status", "\"Status\" IN ('active', 'trialing', 'past_due', 'canceled', 'expired', 'suspended')");

                            t.HasCheckConstraint("CK_Subscriptions_Timeline", "\"ExpiresAt\" IS NULL OR \"ExpiresAt\" >= \"StartedAt\"");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProxyHarbor.Domain.ValidationRun", b =>
                {
                    b.HasOne("ProxyHarbor.Domain.CheckerNode", "CheckerNode")
                        .WithMany("ValidationRuns")
                        .HasForeignKey("CheckerNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CheckerNode");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnEndpoint", b =>
                {
                    b.HasOne("ProxyHarbor.Domain.VpnSource", "FirstSource")
                        .WithMany()
                        .HasForeignKey("FirstSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FirstSource");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnEndpointSource", b =>
                {
                    b.HasOne("ProxyHarbor.Domain.VpnEndpoint", "VpnEndpoint")
                        .WithMany("Sources")
                        .HasForeignKey("VpnEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProxyHarbor.Domain.VpnSource", "VpnSource")
                        .WithMany("Endpoints")
                        .HasForeignKey("VpnSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VpnEndpoint");

                    b.Navigation("VpnSource");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.AccessBlockRule", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Administrator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.PaymentOrder", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ProxyAccessBucket", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ReferralRelationship", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "ReferredUser")
                        .WithOne("ReferredBy")
                        .HasForeignKey("ProxyHarbor.Infrastructure.ReferralRelationship", "ReferredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "ReferrerUser")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferrerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferredUser");

                    b.Navigation("ReferrerUser");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ReferralReward", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.PaymentOrder", "PaymentOrder")
                        .WithMany()
                        .HasForeignKey("PaymentOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProxyHarbor.Infrastructure.ReferralRelationship", "ReferralRelationship")
                        .WithMany("Rewards")
                        .HasForeignKey("ReferralRelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentOrder");

                    b.Navigation("ReferralRelationship");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.SiteVisitLog", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.SubscriptionAdminAction", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProxyHarbor.Infrastructure.UserSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramChat", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithOne("TelegramChat")
                        .HasForeignKey("ProxyHarbor.Infrastructure.TelegramChat", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramConversationMessage", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProxyHarbor.Infrastructure.TelegramOutboundMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboundMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProxyHarbor.Infrastructure.TelegramChat", "TelegramChat")
                        .WithMany()
                        .HasForeignKey("TelegramChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("TelegramChat");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.TelegramOutboundMessage", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.TelegramChat", "TelegramChat")
                        .WithMany()
                        .HasForeignKey("TelegramChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramChat");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserApiToken", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithMany("ApiTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserApiTokenRequest", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.UserApiToken", "UserApiToken")
                        .WithMany("Requests")
                        .HasForeignKey("UserApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserApiToken");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserNotification", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserSubscription", b =>
                {
                    b.HasOne("ProxyHarbor.Infrastructure.ApplicationUser", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("ProxyHarbor.Infrastructure.UserSubscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.CheckerNode", b =>
                {
                    b.Navigation("ValidationRuns");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnEndpoint", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("ProxyHarbor.Domain.VpnSource", b =>
                {
                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ApplicationUser", b =>
                {
                    b.Navigation("ApiTokens");

                    b.Navigation("Referrals");

                    b.Navigation("ReferredBy");

                    b.Navigation("Subscription");

                    b.Navigation("TelegramChat");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.ReferralRelationship", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("ProxyHarbor.Infrastructure.UserApiToken", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
