version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule: { interval: weekly }
    groups:
      dotnet:
        patterns: ['Microsoft.*', 'Npgsql.*']
  - package-ecosystem: npm
    directory: /src/proxyharbor-web
    schedule: { interval: weekly }
    groups:
      frontend:
        patterns: ['*']
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
