import { useCallback, useEffect, useState } from 'react'
import { Activity, ArrowRight, Check, Network, Plus, RefreshCw, Server, Trash2, Workflow, X } from 'lucide-react'
import { ToastSignal } from './components/Toasts'
import { Toggle } from './components/Toggle'
import { currentLocale } from './i18n'

const API = import.meta.env.VITE_API_URL ?? ''

type CheckerNode = {id:string;name:string;host:string;sshPort:number;sshUsername:string;enabled:boolean;concurrency:number;batchSize:number;createdAt:string;updatedAt:string;lastHeartbeatAt?:string;lastLeaseAt?:string;lastCompletedAt?:string;currentLeaseId?:string;currentLeaseUntil?:string;agentVersion?:string;remoteAddress?:string;deploymentStatus:string;lastError?:string;completedChecks:number;aliveChecks:number;hostKeyFingerprint?:string;online:boolean;busy:boolean}
type CheckerNodeList = {image:string;nativeAssetBaseUrl:string;items:CheckerNode[]}

/** Управление внешними VPS, которые забирают непересекающиеся партии проверок. */
export default function AdminCheckerNodesPage(){
  const [data,setData]=useState<CheckerNodeList|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [dialog,setDialog]=useState<{mode:'add'|'deploy'|'delete';node?:CheckerNode}|null>(null)
  const load=useCallback(async()=>{try{const response=await fetch(`${API}/api/v1/admin/checker-nodes`,{credentials:'include'});if(!response.ok)throw new Error(await responseMessage(response,'Узлы проверки недоступны'));setData(await response.json() as CheckerNodeList);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Узлы проверки недоступны')}},[])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);const refresh=window.setInterval(()=>void load(),30000);return()=>{window.clearTimeout(timer);window.clearInterval(refresh)}},[load])
  const update=async(node:CheckerNode,patch:Partial<CheckerNode>)=>{setBusy(node.id);try{const next={...node,...patch};const response=await fetch(`${API}/api/v1/admin/checker-nodes/${node.id}`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:next.enabled,concurrency:next.concurrency,batchSize:next.batchSize})});if(!response.ok)throw new Error(await responseMessage(response,'Настройки узла не сохранены'));await load()}catch(reason){setError(reason instanceof Error?reason.message:'Настройки узла не сохранены')}finally{setBusy('')}}
  const nodes=data?.items??[];const online=nodes.filter(node=>node.online).length;const active=nodes.filter(node=>node.busy).length;const checks=nodes.reduce((sum,node)=>sum+node.completedChecks,0)
  return <section className="admin-section checker-admin-section" aria-labelledby="admin-checkers-title"><AdminPageHeader id="admin-checkers-title" title="Узлы проверки"><div className="checker-heading-actions"><button className="icon-button" aria-label="Обновить узлы" onClick={()=>void load()}><RefreshCw/></button><button className="primary-admin-button" onClick={()=>setDialog({mode:'add'})}><Plus/>Подключить VPS</button></div></AdminPageHeader><ToastSignal kind="error" message={error}/>
    <div className="admin-summary-grid compact-summary checker-summary"><article><span className="summary-icon"><Server/></span><div><small>Подключено</small><strong>{nodes.length}</strong><p>можно добавлять новые VPS</p></div></article><article><span className="summary-icon"><Activity/></span><div><small>На связи</small><strong>{online}</strong><p>heartbeat не старше 2 минут</p></div></article><article><span className="summary-icon"><Workflow/></span><div><small>В работе</small><strong>{active}</strong><p>исполняют партии</p></div></article><article><span className="summary-icon"><Check/></span><div><small>Проверено узлами</small><strong>{formatNumber(checks)}</strong><p>накопительный счётчик</p></div></article></div>
    <section className="admin-card checker-registry"><div className="card-heading"><div><span className="kicker">DISTRIBUTED VALIDATION</span><h2>Внешние VPS</h2><p>SSH-пароль используется только при установке. Истёкшая аренда автоматически возвращается в очередь, а основной сервер остаётся резервным проверяющим.</p></div>{data&&<code className="checker-image">{data.image}</code>}</div><div className="checker-node-list">{data===null?<div className="empty-state"><RefreshCw className="spin"/>Загружаем узлы…</div>:nodes.length===0?<div className="empty-state"><Network/>Внешние узлы ещё не подключены.</div>:nodes.map(node=><article key={node.id} className={!node.enabled?'disabled':''}><div className="checker-node-identity"><span className={`checker-node-indicator ${node.online?'online':''}`}/><div><b>{node.name}</b><small>{node.host}:{node.sshPort} · {node.sshUsername}{node.agentVersion&&` · v${node.agentVersion}`}</small></div></div><div className="checker-node-health"><span className={`state-pill ${node.online?'active':''}`}>{node.online?node.busy?'Проверяет':'На связи':node.enabled?'Не на связи':'Отключён'}</span><small>{node.lastHeartbeatAt?`Heartbeat ${timeAgo(node.lastHeartbeatAt)}`:'Heartbeat ещё не получен'} · {node.deploymentStatus}</small>{node.lastError&&<em title={node.lastError}>{node.lastError}</em>}</div><label>Параллельно<input type="number" min="1" max="1000" value={node.concurrency} onChange={event=>setData(current=>current?{...current,items:current.items.map(item=>item.id===node.id?{...item,concurrency:Number(event.target.value)}:item)}:current)}/></label><label>Партия<input type="number" min="1" max="10000" value={node.batchSize} onChange={event=>setData(current=>current?{...current,items:current.items.map(item=>item.id===node.id?{...item,batchSize:Number(event.target.value)}:item)}:current)}/></label><div className="checker-node-stats"><b>{formatNumber(node.completedChecks)}</b><small>проверок · {formatNumber(node.aliveChecks)} рабочих</small></div><div className="checker-node-actions"><Toggle checked={node.enabled} onChange={enabled=>void update(node,{enabled})} label="Активен"/><button className="table-action" disabled={busy===node.id} onClick={()=>void update(node,{})}><Check/>Сохранить</button><button className="icon-button" data-tooltip="Переустановить агент и сменить токен" aria-label={`Переустановить агент ${node.name}`} onClick={()=>setDialog({mode:'deploy',node})}><RefreshCw/></button><button className="icon-button danger" data-tooltip="Удалить агент с VPS" aria-label={`Удалить узел ${node.name}`} onClick={()=>setDialog({mode:'delete',node})}><Trash2/></button></div></article>)}</div></section>
    {dialog&&<CheckerNodeDialog value={dialog} busy={busy==='dialog'} onClose={()=>setDialog(null)} onComplete={async()=>{setDialog(null);await load()}} onBusy={value=>setBusy(value?'dialog':'')} onError={setError}/>}</section>
}

function CheckerNodeDialog({value,busy,onClose,onComplete,onBusy,onError}:{value:{mode:'add'|'deploy'|'delete';node?:CheckerNode};busy:boolean;onClose:()=>void;onComplete:()=>Promise<void>;onBusy:(value:boolean)=>void;onError:(message:string)=>void}){
  const [form,setForm]=useState({name:'',host:'',sshPort:22,sshUsername:'root',password:'',concurrency:200,batchSize:400})
  const submit=async(event:React.FormEvent)=>{event.preventDefault();onBusy(true);onError('');try{const node=value.node;const url=value.mode==='add'?`${API}/api/v1/admin/checker-nodes`:value.mode==='deploy'?`${API}/api/v1/admin/checker-nodes/${node?.id}/deploy`:`${API}/api/v1/admin/checker-nodes/${node?.id}`;const response=await fetch(url,{method:value.mode==='add'?'POST':value.mode==='delete'?'DELETE':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(value.mode==='add'?form:{password:form.password})});if(!response.ok)throw new Error(await responseMessage(response,value.mode==='delete'?'Узел не удалён':'Агент не развёрнут'));setForm(current=>({...current,password:''}));await onComplete()}catch(reason){onError(reason instanceof Error?reason.message:'Операция с VPS не выполнена')}finally{onBusy(false)}}
  const destructive=value.mode==='delete';const title=value.mode==='add'?'Подключить VPS':destructive?'Удалить узел':'Переустановить агент'
  return <div className="source-editor-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className="source-editor-modal checker-node-modal" role="dialog" aria-modal="true" aria-labelledby="checker-node-dialog-title"><div className="source-editor-heading"><div><span className="kicker">CHECKER NODE</span><h2 id="checker-node-dialog-title">{title}</h2><p>{value.mode==='add'?'Система проверит SSH-доступ и запустит агент в существующем Docker либо как защищённую systemd-службу. Другие сервисы VPS не изменяются.':destructive?'Контейнер и его токен будут удалены с VPS, затем запись исчезнет из панели.':'Сохранённый отпечаток SSH-хоста будет проверен, агент заменён, а токен безопасно сменён.'}</p></div><button className="icon-button" aria-label="Закрыть" disabled={busy} onClick={onClose}><X/></button></div><form className="source-editor-form" onSubmit={submit} autoComplete="off">{value.mode==='add'&&<div className="source-editor-grid"><label>Название<input autoFocus required minLength={2} maxLength={100} value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="VPS Германия 1"/></label><label>Публичный IP<input required inputMode="decimal" value={form.host} onChange={event=>setForm({...form,host:event.target.value})} placeholder="203.0.113.10"/></label><label>SSH-порт<input required type="number" min="1" max="65535" value={form.sshPort} onChange={event=>setForm({...form,sshPort:Number(event.target.value)})}/></label><label>SSH-пользователь<input required maxLength={32} value={form.sshUsername} onChange={event=>setForm({...form,sshUsername:event.target.value})}/></label><label>Параллельных проверок<input required type="number" min="1" max="1000" value={form.concurrency} onChange={event=>setForm({...form,concurrency:Number(event.target.value)})}/></label><label>Размер партии<input required type="number" min="1" max="10000" value={form.batchSize} onChange={event=>setForm({...form,batchSize:Number(event.target.value)})}/></label></div>}<label>SSH-пароль<input autoFocus={value.mode!=='add'} required type="password" autoComplete="new-password" minLength={8} maxLength={512} value={form.password} onChange={event=>setForm({...form,password:event.target.value})} placeholder="Используется один раз и не сохраняется"/><small>Пароль существует только в памяти запроса и не попадает в БД, backup или журнал.</small></label><div className="source-editor-actions"><span/><button type="button" className="secondary-admin-button" disabled={busy} onClick={onClose}>Отмена</button><button className={destructive?'danger-admin-button':'primary-admin-button'} disabled={busy}>{destructive?<Trash2/>:<Server/>}{busy?'Выполняем…':title}</button></div></form></section></div>
}

function AdminPageHeader({id,title,children}:{id:string;title:string;children?:React.ReactNode}){
  return <header className="admin-page-heading"><nav className="admin-breadcrumb" aria-label="Положение в панели управления"><a href="/admin">Панель управления</a><ArrowRight aria-hidden="true"/><h1 id={id}>{title}</h1></nav>{children&&<div className="admin-heading-actions">{children}</div>}</header>
}

function formatNumber(value?:number){return value===undefined?'—':value.toLocaleString(currentLocale())}
function timeAgo(value:string){const sec=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));const formatter=new Intl.RelativeTimeFormat(currentLocale(),{numeric:'auto'});if(sec<60)return formatter.format(-sec,'second');if(sec<3600)return formatter.format(-Math.floor(sec/60),'minute');if(sec<86400)return formatter.format(-Math.floor(sec/3600),'hour');return formatter.format(-Math.floor(sec/86400),'day')}
async function responseMessage(response:Response,fallback:string){try{const problem=await response.json() as {title?:string;detail?:string;message?:string;error?:string};const message=problem.detail||problem.message||problem.title;return [message,problem.error&&problem.error!==message?problem.error:''].filter(Boolean).join(' · ')||fallback}catch{return fallback}}
