import { useCallback, useEffect, useState, type KeyboardEvent, type ReactNode } from 'react'
import { ArrowRight, CalendarClock, Clock3, CreditCard, HelpCircle, Receipt, RefreshCw, Settings2, ShieldCheck, ShieldOff, X } from 'lucide-react'
import { currentLocale, useI18n } from './i18n'
import { Toggle } from './components/Toggle'
import { ToastSignal } from './components/Toasts'

type PagedResult<T> = { items:T[];page:number;pageSize:number;total:number }
type PaymentProduct = { code:string;name:string;plan:string;durationDays:number;amountMinor:number;discountPercent:number;fullDailyPriceMinor:number;savingsMinor:number;currency:string;description:string }
type PaymentOrder = { id:string;productCode:string;plan:string;provider:string;paymentMethod:string;paymentInstrument?:string;amountMinor:number;currency:string;status:string;createdAt:string;paidAt?:string }
type AdminPaymentProduct = PaymentProduct & {enabled:boolean}
type AdminPaymentProviderOperational = { state:'disabled'|'configuration_required'|'healthy'|'pending'|'awaiting_first_payment'|'retest_required'|'webhook_attention'|'no_successful_payments';attention?:string;totalOrders:number;pendingOrders:number;paidOrders:number;paidAfterConfigurationUpdate:number;failedOrders:number;canceledOrders:number;refundedOrders:number;lastOrderAt?:string;lastPaidAt?:string;webhookRequired:boolean;directReconciliationSupported:boolean }
type AdminPaymentProvider = { code:string;name:string;enabled:boolean;merchantId:string;publicId:string;testMode:boolean;secretConfigured:boolean;secondarySecretConfigured:boolean;ready:boolean;webhookUrl:string;operational?:AdminPaymentProviderOperational }
type AdminPaymentSettings = { enabled:boolean;configurationUpdatedAt?:string;products:AdminPaymentProduct[];providers:AdminPaymentProvider[] }
type AdminPaymentProviderDraft = AdminPaymentProvider & {secretKey:string;secondarySecret:string;clearSecretKey:boolean;clearSecondarySecret:boolean}
type AdminInvoice = PaymentOrder & {userId:string;userName:string;email:string;providerPaymentId?:string;updatedAt:string}
type InvoicePage = PagedResult<AdminInvoice> & {summary:{status:string;count:number;amountMinor:number}[]}

const API=import.meta.env.VITE_API_URL??''

/** Runtime-настройка тарифов и шлюзов; сохранённые секреты никогда не загружаются в браузер. */
export default function AdminPaymentsPage() {
  const [settings, setSettings] = useState<AdminPaymentSettings | null>(null)
  const [providers, setProviders] = useState<AdminPaymentProviderDraft[]>([])
  const [tab,setTab]=useState<'overview'|'providers'|'invoices'|'tariffs'>('overview')
  const [providerOpen,setProviderOpen]=useState<string|null>(null)
  const [invoices,setInvoices]=useState<InvoicePage|null>(null)
  const [invoicePage,setInvoicePage]=useState(1)
  const [invoiceStatus,setInvoiceStatus]=useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const loadSettings = useCallback(async () => {
    const response = await fetch(`${API}/api/v1/admin/payments`, {credentials:'include'})
    if (!response.ok) { setError(await responseMessage(response,'Настройки оплаты недоступны')); return }
    const value = await response.json() as AdminPaymentSettings
    setSettings(value)
    setProviders(value.providers.map(provider=>({...provider,secretKey:'',secondarySecret:'',clearSecretKey:false,clearSecondarySecret:false})))
    setError('')
  },[])
  useEffect(()=>{const initial=window.setTimeout(()=>void loadSettings(),0);return()=>window.clearTimeout(initial)},[loadSettings])
  const loadInvoices=useCallback(async()=>{const query=new URLSearchParams({page:String(invoicePage),pageSize:'10'});if(invoiceStatus)query.set('status',invoiceStatus);if(providerOpen)query.set('provider',providerOpen);const response=await fetch(`${API}/api/v1/admin/payments/orders?${query}`,{credentials:'include'});if(!response.ok){setError(await responseMessage(response,'Счета недоступны'));return}setInvoices(await response.json() as InvoicePage)},[invoicePage,invoiceStatus,providerOpen])
  useEffect(()=>{if(tab==='overview'||tab==='invoices'||providerOpen){const timer=window.setTimeout(()=>void loadInvoices(),0);return()=>window.clearTimeout(timer)}},[tab,providerOpen,loadInvoices])
  const updateProduct=(code:string,patch:Partial<AdminPaymentProduct>)=>setSettings(current=>{
    if(!current)return current
    const patched=current.products.map(product=>product.code===code?{...product,...patch}:product)
    const daily=patched.find(product=>product.durationDays===1)?.amountMinor??0
    const products=patched.map(product=>{const amountMinor=product.durationDays===1?daily:calculateSubscriptionPrice(daily,product.durationDays,product.discountPercent);return{...product,amountMinor,fullDailyPriceMinor:daily*product.durationDays,savingsMinor:Math.max(0,daily*product.durationDays-amountMinor)}})
    return {...current,products}
  })
  const updateProvider=(code:string,patch:Partial<AdminPaymentProviderDraft>)=>setProviders(current=>current.map(provider=>provider.code===code?{...provider,...patch}:provider))
  const save = async () => {
    if (!settings) return
    setBusy(true);setError('');setNotice('')
    const response=await fetch(`${API}/api/v1/admin/payments`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:settings.enabled,products:settings.products,providers:providers.map(provider=>({code:provider.code,enabled:provider.enabled,merchantId:provider.merchantId,publicId:provider.publicId,testMode:provider.testMode,secretKey:provider.secretKey||null,secondarySecret:provider.secondarySecret||null,clearSecretKey:provider.clearSecretKey,clearSecondarySecret:provider.clearSecondarySecret}))})})
    if(!response.ok){setError(await responseMessage(response,'Не удалось сохранить настройки'));setBusy(false);return}
    const value=await response.json() as AdminPaymentSettings
    setSettings(value);setProviders(value.providers.map(provider=>({...provider,secretKey:'',secondarySecret:'',clearSecretKey:false,clearSecondarySecret:false})));setNotice('Настройки применены без перезапуска сервиса.');setBusy(false)
  }
  return <section className="admin-section payment-settings" aria-labelledby="admin-payments-title">
    <AdminPageHeader id="admin-payments-title" title="Оплата"><button className="primary-admin-button" disabled={!settings||busy} onClick={()=>void save()}><ShieldCheck/>{busy?'Сохраняем…':'Сохранить изменения'}</button></AdminPageHeader>
    <ToastSignal kind="error" message={error}/><ToastSignal kind="success" message={notice}/>
    {!settings?<div className="admin-card payment-settings-loading"><RefreshCw className="spin"/>Загружаем настройки…</div>:<>
      <AdminTabs value={tab} onChange={value=>setTab(value as typeof tab)} items={[["overview","Обзор"],["providers","Провайдеры"],["invoices","Счета"],["tariffs","Тарифы"]]}/>
      {tab==='overview'&&<><section className="admin-card billing-master-switch"><div><span className="kicker">ГЛОБАЛЬНЫЙ СТАТУС</span><h2>Приём платежей</h2><p>Включайте после настройки хотя бы одного шлюза и проверки юридических данных.</p></div><Toggle checked={settings.enabled} onChange={checked=>setSettings({...settings,enabled:checked})} label={settings.enabled?'Включён':'Выключен'}/></section><div className="billing-overview-grid"><article className="admin-card"><Receipt/><small>Счетов в реестре</small><strong>{invoices?.total??'—'}</strong><button onClick={()=>setTab('invoices')}>Открыть <ArrowRight/></button></article><article className="admin-card"><CreditCard/><small>Готовых шлюзов</small><strong>{providers.filter(x=>x.ready).length} / {providers.length}</strong><button onClick={()=>setTab('providers')}>Настроить <ArrowRight/></button></article><article className="admin-card"><CalendarClock/><small>Активных тарифов</small><strong>{settings.products.filter(x=>x.enabled).length}</strong><button onClick={()=>setTab('tariffs')}>Изменить <ArrowRight/></button></article></div></>}
      {tab==='tariffs'&&<section className="admin-card payment-products-settings"><div className="card-heading"><div><span className="kicker">ТАРИФЫ</span><h2>Сроки и ценовая политика</h2><p>Базовая цена — 99 ₽ за день. Для длительных периодов действует прогрессивная скидка: 350 ₽ за неделю, 690 ₽ за месяц и 1 890 ₽ за квартал. Telegram Stars пересчитываются автоматически.</p></div></div><div>{[...settings.products].sort((a,b)=>a.durationDays-b.durationDays).map(product=><article key={product.code}><Toggle checked={product.enabled} onChange={checked=>updateProduct(product.code,{enabled:checked})} label="Доступен"/><label>Период<input disabled value={subscriptionPeriodName(product.durationDays)}/></label><label>Цена, ₽<input type="number" disabled={product.durationDays!==1} min="0.01" max="10000000" step="0.01" value={(product.amountMinor/100).toString()} onChange={event=>updateProduct(product.code,{amountMinor:Math.round(Number(event.target.value)*100)})}/></label><label>Скидка, %<input type="number" min="0" max="99" step="0.01" disabled={product.durationDays===1||product.durationDays===365} value={product.discountPercent} onChange={event=>updateProduct(product.code,{discountPercent:Number(event.target.value)})}/></label><div className="tariff-policy-summary"><b>{product.durationDays===1?'Базовая цена':money(product.amountMinor,product.currency)}</b>{product.savingsMinor>0&&<small><s>{money(product.fullDailyPriceMinor,product.currency)}</s> · экономия {money(product.savingsMinor,product.currency)}</small>}</div><label className="payment-description">Описание<input maxLength={300} value={product.description} onChange={event=>updateProduct(product.code,{description:event.target.value})}/></label></article>)}</div></section>}
      {tab==='providers'&&<ProviderCards providers={providers} onOpen={code=>{setInvoices(null);setProviderOpen(code)}}/>}
      {tab==='invoices'&&<InvoiceRegistry data={invoices} status={invoiceStatus} onStatus={value=>{setInvoiceStatus(value);setInvoicePage(1)}} page={invoicePage} onPage={setInvoicePage}/>}
      {providerOpen&&<ProviderDialog provider={providers.find(x=>x.code===providerOpen)!} invoices={invoices} busy={busy} onClose={()=>setProviderOpen(null)} onUpdate={updateProvider} onSave={()=>void save()}/>}
    </>}
  </section>
}

function needsMerchantId(code:string){return !['stripe','cloudpayments','nowpayments'].includes(code)}
function merchantFieldLabel(code:string){return code==='yookassa'?'Shop ID':code==='yoomoney'?'Номер кошелька':code==='robokassa'?'Merchant Login':code==='tbank'?'Terminal Key':code==='cryptomus'?'Merchant UUID':'Merchant ID'}
function primarySecretLabel(code:string){return code==='yookassa'?'Secret Key':code==='yoomoney'?'Секрет HTTP-уведомлений':code==='cloudpayments'?'API Secret':code==='robokassa'?'Пароль №1':code==='tbank'?'Пароль терминала':code==='cryptomus'?'Payment API key':code==='nowpayments'?'API key':'Secret Key'}
function secondarySecretLabel(code:string){return code==='robokassa'?'Пароль №2':code==='nowpayments'?'IPN secret':'Webhook Secret'}
function needsSecondarySecret(code:string){return code==='robokassa'||code==='stripe'||code==='nowpayments'}

type PaymentProviderHelp = {accountPath:string;officialUrl:string;steps:string[];webhookNote:string}

const paymentProviderHelp:Record<string,PaymentProviderHelp>={
  yookassa:{accountPath:'Личный кабинет → Настройки → Магазин и Интеграция → Ключи API',officialUrl:'https://yookassa.ru/developers/using-api/interaction-format',steps:['Скопируйте shopId магазина.','Выпустите и сохраните секретный ключ API.','В разделе «Интеграция → HTTP-уведомления» добавьте указанный ниже URL и включите событие payment.succeeded.'],webhookNote:'ЮKassa принимает только HTTPS URL на порту 443 или 8443.'},
  yoomoney:{accountPath:'Кошелёк ЮMoney → Настройки → HTTP-уведомления',officialUrl:'https://yoomoney.ru/docs/payment-buttons/using-api/notifications',steps:['Укажите номер кошелька, на который будут поступать переводы.','Включите HTTP-уведомления и вставьте указанный ниже URL.','Скопируйте созданный секрет уведомлений в поле формы.'],webhookNote:'Для одного кошелька ЮMoney можно указать только один адрес HTTP-уведомлений.'},
  cloudpayments:{accountPath:'Back Office CloudPayments → Сайты и уведомления',officialUrl:'https://developers.cloudpayments.ru/',steps:['Скопируйте Public ID сайта и API Secret из Back Office.','Откройте настройки уведомлений и включите уведомление Pay.','Укажите URL ниже, метод POST, кодировку UTF-8 и формат CloudPayments.'],webhookNote:'API Secret одновременно используется для API-аутентификации и проверки HMAC уведомлений.'},
  robokassa:{accountPath:'Личный кабинет Robokassa → Магазины → Технические настройки',officialUrl:'https://docs.robokassa.ru/ru/',steps:['Скопируйте Merchant Login, Пароль №1 и Пароль №2.','Для Result URL укажите адрес ниже и метод POST.','Для подписей выберите алгоритм SHA-256; тестовый режим включайте только с тестовыми паролями.'],webhookNote:'Пароль №1 подписывает создание счёта, Пароль №2 проверяет ResultURL.'},
  tbank:{accountPath:'Т-Бизнес → Интернет-эквайринг → Магазины → Терминалы → Настроить',officialUrl:'https://developer.tbank.ru/eacq/intro/developer/terminal',steps:['Скопируйте TerminalKey выбранного терминала.','Скопируйте пароль терминала — он чувствителен к регистру.','NotificationURL передаётся сервисом при создании каждого платежа; при желании тот же URL можно сохранить в настройках терминала.'],webhookNote:'Терминал должен быть рабочим, а не неактивным; для проверки используйте отдельный тестовый терминал.'},
  stripe:{accountPath:'Stripe Dashboard → Developers → API keys и Webhooks',officialUrl:'https://docs.stripe.com/keys',steps:['Скопируйте серверный Secret key нужного режима: sk_test_… или sk_live_….','В разделе Webhooks создайте endpoint с URL ниже.','Подпишите endpoint на checkout.session.completed и скопируйте его Signing secret whsec_….'],webhookNote:'API Secret и Webhook Signing secret — разные ключи; тестовые и рабочие ключи нельзя смешивать.'},
  cryptomus:{accountPath:'Cryptomus → Business → Merchants → ваш проект → Settings',officialUrl:'https://doc.cryptomus.com/ru',steps:['Создайте Merchant и подтвердите домен, если сервис запросит модерацию.','Скопируйте UUID мерчанта и Payment API key.','Callback URL передаётся автоматически при создании платежа; адрес ниже показан для проверки.'],webhookNote:'Нужен именно Payment API key, а не Payout API key.'},
  nowpayments:{accountPath:'NOWPayments Account → Store Settings',officialUrl:'https://nowpayments.io/help/about-nowpayments/how-to-start/how-to-set-up-an-account',steps:['Добавьте кошелёк для получения средств и сохраните настройки магазина.','Создайте API key через Add new key.','Сгенерируйте IPN Secret и сохраните его сразу: сервис показывает секрет только один раз.'],webhookNote:'IPN callback передаётся автоматически при создании счёта; API key и IPN Secret вводятся в разные поля.'}
}

function providerOperationalLabel(provider:AdminPaymentProvider){const state=provider.operational?.state;if(state==='healthy')return `${provider.operational?.paidAfterConfigurationUpdate??provider.operational?.paidOrders??0} оплат после настройки`;if(state==='pending')return `Ожидают подтверждения: ${provider.operational?.pendingOrders??0}`;if(state==='retest_required')return 'Нужна повторная тестовая оплата';if(state==='webhook_attention')return 'Webhook требует проверки';if(state==='no_successful_payments')return 'Нет подтверждённых оплат';if(state==='awaiting_first_payment')return 'Ожидает первой оплаты';return provider.ready?'Реквизиты заполнены':'Требуется настройка'}
function providerOperationalTone(provider:AdminPaymentProvider){const state=provider.operational?.state;return state==='healthy'?'healthy':state==='retest_required'||state==='webhook_attention'||state==='no_successful_payments'?'attention':''}

function ProviderCards({providers,onOpen}:{providers:AdminPaymentProviderDraft[];onOpen:(code:string)=>void}){return <section className="provider-card-grid">{providers.map(provider=><article className="admin-card provider-card" key={provider.code}><div className="provider-card-icon"><CreditCard/></div><div><strong>{provider.name}</strong><small>{provider.ready?'Реквизиты заполнены':'Требуется настройка'}</small></div><span className={`state-pill ${provider.enabled&&provider.ready?'active':''}`}>{provider.enabled?'Включён':'Выключен'}</span><div className={`provider-operational-note ${providerOperationalTone(provider)}`}>{providerOperationalTone(provider)==='healthy'?<ShieldCheck/>:providerOperationalTone(provider)==='attention'?<ShieldOff/>:<Clock3/>}<span><b>{providerOperationalLabel(provider)}</b>{provider.operational?.attention&&<small>{provider.operational.attention}</small>}</span></div><div className="provider-card-actions"><button aria-label={`Настройки ${provider.name}`} onClick={()=>onOpen(provider.code)}><Settings2/>Настройки</button><button aria-label={`Как подключить ${provider.name}`} onClick={()=>onOpen(provider.code)}><HelpCircle/>Как подключить</button></div></article>)}</section>}

function ProviderDialog({provider,invoices,busy,onClose,onUpdate,onSave}:{provider:AdminPaymentProviderDraft;invoices:InvoicePage|null;busy:boolean;onClose:()=>void;onUpdate:(code:string,patch:Partial<AdminPaymentProviderDraft>)=>void;onSave:()=>void}){
  const help=paymentProviderHelp[provider.code]
  const ignoreAutofill={autoComplete:'off','data-1p-ignore':true,'data-lpignore':'true','data-form-type':'other'} as const
  return <div className="source-editor-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="source-editor-modal provider-modal" role="dialog" aria-modal="true" aria-label={`Настройки ${provider.name}`}><div className="source-editor-heading"><div><span className="kicker">PAYMENT PROVIDER</span><h2>{provider.name}</h2><p>Реквизиты шлюза изолированы; сохранённые секреты никогда не возвращаются в браузер.</p></div><button className="icon-button" aria-label={`Закрыть настройки ${provider.name}`} onClick={onClose}><X/></button></div>
    <section className="provider-help" aria-labelledby={`provider-help-${provider.code}`}><div className="provider-help-heading"><span><HelpCircle/></span><div><small>ПОМОЩЬ ПО ПОДКЛЮЧЕНИЮ</small><h3 id={`provider-help-${provider.code}`}>Подключение {provider.name} за 3 шага</h3><b>{help.accountPath}</b></div></div><ol>{help.steps.map(step=><li key={step}>{step}</li>)}</ol><div className="provider-help-footer"><p>{help.webhookNote}</p><a href={help.officialUrl} target="_blank" rel="noreferrer">Открыть официальную инструкцию <ArrowRight/></a></div></section>
    <div className="provider-modal-status"><Toggle checked={provider.enabled} onChange={checked=>onUpdate(provider.code,{enabled:checked})} label="Принимать платежи"/><span className={`state-pill ${provider.ready?'active':''}`}>{provider.ready?'Готов':'Не настроен'}</span></div>{provider.operational&&<div className={`provider-operational-detail ${providerOperationalTone(provider)}`}><div>{providerOperationalTone(provider)==='healthy'?<ShieldCheck/>:providerOperationalTone(provider)==='attention'?<ShieldOff/>:<Clock3/>}<span><b>{providerOperationalLabel(provider)}</b><small>Счетов: {provider.operational.totalOrders} · оплачено: {provider.operational.paidOrders} · ожидает: {provider.operational.pendingOrders}</small></span></div>{provider.operational.attention&&<p>{provider.operational.attention}</p>}</div>}
    <div className="provider-fields">{needsMerchantId(provider.code)&&<label>{merchantFieldLabel(provider.code)}<input {...ignoreAutofill} name={`gateway-${provider.code}-merchant`} spellCheck={false} maxLength={256} value={provider.merchantId} onChange={event=>onUpdate(provider.code,{merchantId:event.target.value})}/></label>}{provider.code==='cloudpayments'&&<label>Public ID<input {...ignoreAutofill} name="gateway-cloudpayments-public-id" spellCheck={false} maxLength={256} value={provider.publicId} onChange={event=>onUpdate(provider.code,{publicId:event.target.value})}/></label>}<label>{primarySecretLabel(provider.code)}<input {...ignoreAutofill} name={`gateway-${provider.code}-primary-secret`} type="password" spellCheck={false} maxLength={4096} placeholder={provider.secretConfigured?'Сохранён · введите для замены':'Введите секрет'} value={provider.secretKey} onChange={event=>onUpdate(provider.code,{secretKey:event.target.value,clearSecretKey:false})}/><small>{provider.secretConfigured?'Секрет настроен и скрыт':'Секрет ещё не задан'}</small></label>{needsSecondarySecret(provider.code)&&<label>{secondarySecretLabel(provider.code)}<input {...ignoreAutofill} name={`gateway-${provider.code}-secondary-secret`} type="password" spellCheck={false} maxLength={4096} placeholder={provider.secondarySecretConfigured?'Сохранён · введите для замены':'Введите второй секрет'} value={provider.secondarySecret} onChange={event=>onUpdate(provider.code,{secondarySecret:event.target.value,clearSecondarySecret:false})}/></label>}</div>
    {provider.code==='robokassa'&&<Toggle checked={provider.testMode} onChange={checked=>onUpdate(provider.code,{testMode:checked})} label="Тестовый режим"/>}<div className="webhook-box"><small>Webhook URL</small><code>{provider.webhookUrl}</code></div><div className="provider-secret-actions">{provider.secretConfigured&&<Toggle danger checked={provider.clearSecretKey} onChange={checked=>onUpdate(provider.code,{clearSecretKey:checked,secretKey:''})} label="Удалить основной секрет"/>}{provider.secondarySecretConfigured&&<Toggle danger checked={provider.clearSecondarySecret} onChange={checked=>onUpdate(provider.code,{clearSecondarySecret:checked,secondarySecret:''})} label="Удалить второй секрет"/>}</div><div className="source-editor-actions"><span/><button className="secondary-admin-button" onClick={onClose}>Закрыть</button><button className="primary-admin-button" onClick={onSave} disabled={busy}><ShieldCheck/>{busy?'Сохраняем…':'Сохранить'}</button></div><div className="provider-invoices"><h3>Последние счета через {provider.name}</h3><InvoiceTable data={invoices}/></div></section></div>
}

function InvoiceRegistry({data,status,onStatus,page,onPage}:{data:InvoicePage|null;status:string;onStatus:(value:string)=>void;page:number;onPage:(value:number)=>void}){const totalPages=Math.max(1,Math.ceil((data?.total??0)/10));return <section className="admin-card invoice-registry"><div className="card-heading"><div><span className="kicker">ЕДИНЫЙ РЕЕСТР</span><h2>Счета</h2></div><span className="section-count">{data?.total??0}</span></div><AdminTabs value={status} onChange={onStatus} items={[["","Все"],["pending","Ожидают"],["paid","Оплачены"],["failed","Ошибки"],["canceled","Отменены"],["refunded","Возвраты"]]}/><InvoiceTable data={data}/>{data&&data.total>10&&<ProxyPagination page={page} pageSize={10} total={data.total} totalPages={totalPages} onPageChange={onPage} onPageSizeChange={()=>{}}/>}</section>}
function InvoiceTable({data}:{data:InvoicePage|null}){return <div className="admin-data-table invoice-table"><div className="admin-data-head"><span>Счёт / клиент</span><span>Способ оплаты</span><span>Сумма</span><span>Статус</span><span>Создан</span></div>{!data?<div className="empty-state"><RefreshCw className="spin"/>Загружаем счета…</div>:data.items.length===0?<div className="empty-state"><Receipt/>Счетов в этой группе пока нет.</div>:data.items.map(item=><article key={item.id}><span><b>#{item.id.slice(0,8)}</b><small>{item.email||item.userName}</small></span><span><b>{providerLabel(item.provider)}</b><small>{item.paymentInstrument||item.paymentMethod}{item.providerPaymentId?` · ID ${item.providerPaymentId}`:''}</small></span><b>{money(item.amountMinor,item.currency)}</b><em className={`payment-status ${item.status}`}>{paymentStatusLabel(item.status)}</em><time>{new Date(item.createdAt).toLocaleString('ru-RU')}</time></article>)}</div>}


function AdminPageHeader({id,title,children}:{id:string;title:string;children?:ReactNode}){
  return <header className="admin-page-heading"><nav className="admin-breadcrumb" aria-label="Положение в панели управления"><a href="/admin">Панель управления</a><ArrowRight aria-hidden="true"/><h1 id={id}>{title}</h1></nav>{children&&<div className="admin-heading-actions">{children}</div>}</header>
}

function AdminTabs({value,onChange,items,ariaLabel='Разделы страницы',idPrefix}:{value:string;onChange:(value:string)=>void;items:[string,string][];ariaLabel?:string;idPrefix?:string}){
  const activate=(index:number,event:KeyboardEvent<HTMLButtonElement>)=>{const buttons=event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role="tab"]');const button=buttons?.[index];if(!button)return;button.focus();onChange(items[index][0])}
  return <nav className="admin-tabs" role="tablist" aria-label={ariaLabel}>{items.map(([key,label],index)=><button key={key} type="button" id={idPrefix?`${idPrefix}-tab-${key}`:undefined} role="tab" aria-selected={value===key} aria-controls={idPrefix?`${idPrefix}-panel-${key}`:undefined} tabIndex={value===key?0:-1} className={value===key?'active':''} onClick={()=>onChange(key)} onKeyDown={event=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();if(event.key==='ArrowRight')activate((index+1)%items.length,event);else if(event.key==='ArrowLeft')activate((index-1+items.length)%items.length,event);else if(event.key==='Home')activate(0,event);else activate(items.length-1,event)}}>{label}</button>)}</nav>
}

function ProxyPagination({page,pageSize,total,totalPages,onPageChange,onPageSizeChange}:{page:number;pageSize:number;total:number;totalPages:number;onPageChange:(page:number)=>void;onPageSizeChange:(size:number)=>void}){
  const {t}=useI18n();const [jump,setJump]=useState('');const pages=paginationWindow(page,totalPages);const go=(next:number)=>onPageChange(Math.min(totalPages,Math.max(1,next)));const showQuickJump=totalPages>7
  return <nav className={`pagination${showQuickJump?'':' pagination-compact'}`} aria-label={t('quickJump')}><div className="page-sizes"><span>{t('show')}</span>{[10,25,50,100].map(size=><button key={size} className={pageSize===size?'active':''} aria-pressed={pageSize===size} onClick={()=>onPageSizeChange(size)}>{size}</button>)}</div><div className="page-controls"><button aria-label={t('previousPage')} disabled={page===1} onClick={()=>go(page-1)}>←</button>{pages.map((item,index)=>item==='…'?<span key={`ellipsis-${index}`}>…</span>:<button key={item} className={item===page?'active':''} aria-current={item===page?'page':undefined} onClick={()=>go(item)}>{item}</button>)}<button aria-label={t('nextPage')} disabled={page===totalPages} onClick={()=>go(page+1)}>→</button></div>{showQuickJump&&<form className="page-jump" aria-label={t('quickJump')} onSubmit={event=>{event.preventDefault();const value=Number(jump);if(Number.isInteger(value)&&value>0){go(value);setJump('')}}}><input aria-label={t('pageNumber')} inputMode="numeric" min={1} max={totalPages} type="number" placeholder="Стр." value={jump} onChange={event=>setJump(event.target.value)}/><span aria-hidden="true">/ {totalPages}</span><button type="submit" aria-label={t('goToPage')}><ArrowRight size={14}/></button></form>}<p>{t('page',{page,pages:totalPages,total:formatNumber(total)})}</p></nav>
}

function paginationWindow(page:number,totalPages:number):(number|'…')[]{if(totalPages<=7)return Array.from({length:totalPages},(_,index)=>index+1);if(page<=4)return [1,2,3,4,5,'…',totalPages];if(page>=totalPages-3)return [1,'…',totalPages-4,totalPages-3,totalPages-2,totalPages-1,totalPages];return [1,'…',page-1,page,page+1,'…',totalPages]}
function formatNumber(value?:number){return value===undefined?'—':value.toLocaleString(currentLocale())}
function money(minor:number,currency:string){return new Intl.NumberFormat(currentLocale(),{style:'currency',currency}).format(minor/100)}
function calculateSubscriptionPrice(dailyMinor:number,days:number,discount:number){return Math.ceil(dailyMinor*days*(100-discount)/100/100)*100}
function subscriptionPeriodName(days:number){return days===1?'День':days===7?'Неделя':days===30?'Месяц':days===90?'Квартал':days===180?'Полгода':days===365?'Год':`${days} дней`}
function providerLabel(provider:string){return ({yookassa:'ЮKassa',yoomoney:'ЮMoney',cloudpayments:'CloudPayments',robokassa:'Robokassa',tbank:'Т-Банк',stripe:'Stripe',cryptomus:'Cryptomus',nowpayments:'NOWPayments'} as Record<string,string>)[provider]??provider}
function paymentStatusLabel(status:string){return ({pending:'Ожидает оплаты',paid:'Оплачен',failed:'Ошибка',canceled:'Отменён',refunded:'Возвращён'} as Record<string,string>)[status]??status}
async function responseMessage(response:Response,fallback:string){try{const problem=await response.json() as {title?:string;detail?:string;message?:string};return problem.detail||problem.message||problem.title||fallback}catch{return fallback}}
