import type { Language } from './i18n'

type Messages = { download: string; downloading: string; unavailable: string; invalid: string; busy: string; access: string; failed: string; format: string; empty: string; hint: string }

export const clashDownloadMessages: Record<Language, Messages> = {
  ru: { download: 'Скачать Clash YAML', downloading: 'Скачиваем Clash YAML', unavailable: 'Для выбранных фильтров нет свежих полных Clash-конфигураций.', invalid: 'Не удалось экспортировать полные конфигурации. Попробуйте сузить фильтры.', busy: 'Экспорт временно недоступен. Попробуйте ещё раз позже.', access: 'Нет доступа к конфигурациям. Войдите в аккаунт повторно.', failed: 'Не удалось скачать конфигурацию Clash YAML. Попробуйте ещё раз.', format: 'Сервер вернул неожиданный формат конфигурации.', empty: 'Сервер вернул пустую конфигурацию.', hint: 'Ссылки показаны в таблице. Clash YAML скачивается отдельно по выбранным фильтрам и с учётом лимита доступа.' },
  en: { download: 'Download Clash YAML', downloading: 'Downloading Clash YAML', unavailable: 'No fresh, complete Clash configurations match these filters.', invalid: 'Could not export complete configurations. Try narrowing the filters.', busy: 'Export is temporarily unavailable. Please try again later.', access: 'Configuration access denied. Please sign in again.', failed: 'Could not download Clash YAML. Please try again.', format: 'The server returned an unexpected configuration format.', empty: 'The server returned an empty configuration.', hint: 'The table shows connection links. Clash YAML downloads separately using the selected filters and your access limit.' },
  de: { download: 'Clash YAML herunterladen', downloading: 'Clash YAML wird heruntergeladen', unavailable: 'Keine aktuellen, vollständigen Clash-Konfigurationen für diese Filter.', invalid: 'Vollständige Konfigurationen konnten nicht exportiert werden. Grenzen Sie die Filter ein.', busy: 'Der Export ist vorübergehend nicht verfügbar. Versuchen Sie es später erneut.', access: 'Zugriff verweigert. Melden Sie sich erneut an.', failed: 'Clash YAML konnte nicht heruntergeladen werden. Versuchen Sie es erneut.', format: 'Der Server hat ein unerwartetes Konfigurationsformat zurückgegeben.', empty: 'Der Server hat eine leere Konfiguration zurückgegeben.', hint: 'Die Tabelle zeigt Verbindungslinks. Clash YAML wird separat mit den gewählten Filtern und Ihrem Zugriffslimit heruntergeladen.' },
  fr: { download: 'Télécharger Clash YAML', downloading: 'Téléchargement de Clash YAML', unavailable: 'Aucune configuration Clash complète et récente pour ces filtres.', invalid: 'Impossible d’exporter les configurations complètes. Affinez les filtres.', busy: 'L’export est temporairement indisponible. Réessayez plus tard.', access: 'Accès refusé. Reconnectez-vous.', failed: 'Impossible de télécharger Clash YAML. Réessayez.', format: 'Le serveur a renvoyé un format de configuration inattendu.', empty: 'Le serveur a renvoyé une configuration vide.', hint: 'Le tableau affiche les liens de connexion. Clash YAML se télécharge séparément selon les filtres choisis et votre limite d’accès.' },
  zh: { download: '下载 Clash YAML', downloading: '正在下载 Clash YAML', unavailable: '没有符合筛选条件的完整且最新的 Clash 配置。', invalid: '无法导出完整配置，请缩小筛选范围。', busy: '导出暂时不可用，请稍后重试。', access: '无法访问配置，请重新登录。', failed: '无法下载 Clash YAML，请重试。', format: '服务器返回了意外的配置格式。', empty: '服务器返回了空配置。', hint: '表格显示连接链接。Clash YAML 根据所选筛选条件和访问限额单独下载。' },
}
