<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProxyHarbor.Domain\ProxyHarbor.Domain.csproj" />
    <ProjectReference Include="..\ProxyHarbor.Infrastructure\ProxyHarbor.Infrastructure.csproj" />
  </ItemGroup>
</Project>
